[phases.setup]
nixPkgs = ['nodejs_20', 'python312']

[phases.install]
cmds = [
  'corepack enable',
  'chmod +x railway-build.sh',
  './railway-build.sh'
]

[start]
cmd = 'cd backend && uv run python main.py'